#debug: true

server:
  error:
    whitelabel:
      enabled: false


spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: leesh
    username: leesh
    url: jdbc:mariadb://localhost:3306/testdb
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
